development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gopromocodes_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gopromocodes_test
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  host: localhost
  username: gopromocodes
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  database: gopromocodes_production
  pool: 5
  timeout: 5000