development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gopromocodes_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gopromocodes
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username: qnbfosrvfpklce
  password: 769c6b12b9ae08954f634af13876d3e1971f2a0130536becd360fb729f177215
  database: d1qmon0crd30f7
  pool: 5
  timeout: 5000